const changes = {
	'ITEM.TypeSpell': 'Power',
	'ITEM.TypeSpellPl': 'Powers',
	'JOURNALENTRYPAGE.DND5E.Class.SpellSlots': 'Power Slots',
	'JOURNALENTRYPAGE.DND5E.Class.SpellSlotsPerSpellLevel': '—Power Slots per Power Level—',
	'SETTINGS.5eAutoSpellTemplateL':
		'When a power is cast, defaults to begin the process to create the corresponding Measured Template if any (requires TRUSTED or higher player role)',
	'SETTINGS.5eAutoSpellTemplateN': 'Always place Power Template',
	'DND5E.AbilityUseCast': 'Cast Power',
	'DND5E.ActionMSAK': 'Melee Power Attack',
	'DND5E.ActionRSAK': 'Ranged Power Attack',
	'DND5E.AdvancementItemGrantHint': 'Grant the character items (such as equipment, features, or powers) when they reach a certain level.',
	'DND5E.BonusMSAttack': 'Melee Power Attack Bonus',
	'DND5E.BonusMSDamage': 'Melee Power Damage Bonus',
	'DND5E.BonusRSAttack': 'Ranged Power Attack Bonus',
	'DND5E.BonusRSDamage': 'Ranged Power Damage Bonus',
	'DND5E.BonusSpell': 'Global Power Bonuses',
	'DND5E.BonusSpellDC': 'Global Power DC Bonus',
	'DND5E.FilterNoSpells': 'No powers found for this set of filters.',
	'DND5E.NoSpellLevels': 'This character has no esper levels, but you may add powers manually.',
	'DND5E.FlagsSpellCritThreshold': 'Power Critical Hit Threshold',
	'DND5E.FlagsSpellCritThresholdHint': 'An expanded critical hit threshold for power attacks.',
	'DND5E.LongRestHint':
		'Take a long rest? On a long rest you will recover hit points, half your maximum hit dice, class resources, limited use item charges, and power slots.',
	'DND5E.PolymorphKeepOriginAE': 'Keep effects that originate from this actor (i.e. effects not attached to features, items, powers)',
	'DND5E.PolymorphKeepSelf': 'Keep self (just change image and size i.e. for powers like Disguise Self)',
	'DND5E.PolymorphKeepSpellAE': 'Keep effects that originate from your powers?',
	'DND5E.PolymorphKeepSpells': 'Keep powers',
	'DND5E.SpellAbility': 'Power Ability',
	'DND5E.SpellAdd': 'Add Power',
	'DND5E.SpellCastConsume': 'Consume Power Slot?',
	'DND5E.SpellCastNoSlots': 'You have no available {level} power slots with which to cast {name}',
	'DND5E.SpellCastUpcast': 'Cast at Rank',
	'DND5E.SpellcasterLevel': 'Esper Level',
	'DND5E.SpellCastingHeader': 'Power Casting',
	'DND5E.Spellcasting': 'Using a power',
	'DND5E.SpellComponents': 'Power Components',
	'DND5E.SpellCreate': 'Create Power',
	'DND5E.SpellDC': 'Power DC',
	'DND5E.SpellDetails': 'Power Details',
	'DND5E.SpellEffects': 'Power Effects',
	'DND5E.SpellLevel': 'Power Level',
	'DND5E.SpellLevels': 'Power Levels',
	'DND5E.SpellMaterials': 'Using a power Materials',
	'DND5E.SpellName': 'Power Name',
	'DND5E.SpellPrepInnate': 'Talent Using a power',
	'DND5E.SpellPreparation': 'Power Preparation',
	'DND5E.SpellPreparationMode': 'Power Preparation Mode',
	'DND5E.SpellProgression': 'Power Progression',
	'DND5E.SpellSchool': 'Discipline',
	'DND5E.SpellScroll': 'Power Scroll',
	'DND5E.SpellTarget': 'Power Target',
	'DND5E.SpellUsage': 'Power Usage',
	'DND5E.Spellbook': 'Powers',
	'DND5E.spell': 'power',
	'dnd5e-spellpoints.poptitle': 'Power Points System 5e Configuration',
	'dnd5e-spellpoints.form': 'Click the button to open Power Points System 5e Configuration',
	'dnd5e-spellpoints.form-hint': 'Here you can configure module behaviour, power point cost and more.',
	'dnd5e-spellpoints.form-title': 'Power Points Configuration',
	'dnd5e-spellpoints.resourceLabel': 'Power Points Resource',
	'dnd5e-spellpoints.resourceNote': 'This is the name of the resource on Player Character Sheet that represents the power points (default: Power Points).',
	'dnd5e-spellpoints.mixedMode': 'With Mixed Mode enabled every character will get the option to enable Power Points directly in the character sheet.',
	'dnd5e-spellpoints.autoLabel': 'Enable Automatic power points calculation',
	'dnd5e-spellpoints.formulaLabel': 'Automatic power points calculation formula',
	'dnd5e-spellpoints.formulaNote': 'What formula should this module use to calculate the maximum PC power points (default: DMG).',
	'dnd5e-spellpoints.formulaNote2':
		'Choosing Advanced Magic (homebrew), power points will be calculated accordingly to the free homebrew module "Advanced Magic - Power Points System 5e" available for free on',
	'dnd5e-spellpoints.spellPointsCostsTitle': 'Power Point costs',
	'dnd5e-spellpoints.costLabel': 'Power Points cost for Level {slotLevel} slots.',
	'dnd5e-spellpoints.spellPointsCostsNote': "You don't need to change the power point costs if you are using the default powerpoint rules on DMG (page 288).",
	'dnd5e-spellpoints.AMTitle': 'Advanced Magic - Power Points System 5e',
	'dnd5e-spellpoints.AMInstructions':
		'This module allows you to customize powerpoints costs and enabling other options below not used with the default rules. You can find an alternate system available for free on ',
	'dnd5e-spellpoints.enableVariantLabel': 'Use HP as Power Points (Gritty Variant)',
	'dnd5e-spellpoints.enableVariantNote':
		"Enabling this Player's Characters will be able to continue casting power once they run out of power points using their own life at increased cost (see Advanced Magic System)",
	'dnd5e-spellpoints.spLifeCostNote':
		'How many Hit Points Maximum a character will lose casting a power with their own life. This is a multiplier. ex: if set to 2 a character casting a Power with a cost of 2 power points will lose 4 hp max. (default:2)',
	'dnd5e-spellpoints.use-spellpoints': 'This character uses Power Points',
	'dnd5e-spellpoints.createNewResource': 'Please create a new resource named {PowerPoints}',
	'dnd5e-spellpoints.actorNoSP': "{ActorName} doesn't have any resource named {PowerPoints}",
	'dnd5e-spellpoints.notEnoughSp': "{ActorName} doesn't have enough {PowerPoints} to cast this power.",
	'dnd5e-spellpoints.pleaseCreate': "Please create a resource named: '{PowerPoints}' to cast this power.",
	'dnd5e-spellpoints.youNotEnough': "You don't have enough '{PowerPoints}' to cast this power.",
	'dnd5e-spellpoints.spellCost': 'Costs {amount} {PowerPoints}',
	'dnd5e-spellpoints.spellUsingSpellPoints': '{ActorName} cast a power using {powerPointUsed} {PowerPoints}. {remainingPoints} {PowerPoints} remaining.',
	'dnd5e-spellpoints.spellPointsFormula': 'Max Power Points Formula',
	'dnd5e-spellpoints.formulaBaseNote': 'The base formula is added if the character has at least one power slot.',
	'dnd5e-spellpoints.formulaSlotNote': 'The slot formula multiplies the total Power Point costs of the slots that the character would have.',
	'dnd5e-spellpoints.warlockUseSpLabel': 'Warlocks use Power Points',
	'dnd5e-spellpoints.warlockUseSpNote': 'By default warlocks cannot use the powerpoints system, enabling this they will be able to do it like other casters.',
	'dnd5e-spellpoints.chatMessagePrivateLabel': 'Private Power Points usage messages.',
	'dnd5e-spellpoints.chatMessagePrivateNote':
		'Enabling this setting the chat messages about how many Power Points have been used, will be visible by the GM and the current player, other players will not see the message.',
	'TIDY5E.Prepare': 'Prepare Technique',
	'TIDY5E.EditSpell': 'Edit Power',
	'TIDY5E.DeleteSpell': 'Delete Power',
	'TIDY5E.SearchSpell': 'search power',
	'TIDY5E.PreparedSpells': 'Prepared Techniques',
	'TIDY5E.PreparedSpellsMax': "Maximum for prepared techniques (Note: do not use 'Override' mode on the active effect')",
	'TIDY5E.SpellClass': 'Power Class',
	'TIDY5E.Spellbook': 'Powers',
	'TIDY5E.SpellSchool': 'Discipline',
	'TIDY5E.Settings.MulticlassSpellbookFilterLabel': 'Multiclass Powers Filter',
	'TIDY5E.Settings.ClassicControls.hint':
		'Always shows item controls this will not disable the right click menu. Only applies for PC item/power inventory in list layout.',
	'TIDY5E.Settings.HideSpellbookTabNpc.name': 'Hide Powers tab on NPC',
	'TIDY5E.Settings.HideSpellbookTabNpc.hint': 'By default the powers tab on NPC is moved on the attributes tab. Disable this for never do that.',
	'TIDY5E.Settings.DefaultActionsTab.spellbook': 'Powers',
	'TIDY5E.Settings.HideSpellSlotMarker.name': 'Hide Power Slot Marker on sheet.',
	'TIDY5E.Settings.HideSpellSlotMarker.hint':
		'Enable to hide the colored power slot marker, this is usually useful when the power points variant rule is use.',
	'TIDY5E.Settings.EnableSpellLevelButtons.name': 'Enable Power Level Buttons.',
	'TIDY5E.Settings.EnableSpellLevelButtons.hint': 'Enable to replaces the power level select dropdown menu with buttons.',
	'TIDY5E.Settings.SpellClassFilterSelect.name': 'Enable Multiclass Powers filter',
	'TIDY5E.Settings.SpellClassFilterIconReplace.name': 'Cover power icon with class icon',
	'TIDY5E.Settings.SpellClassFilterIconReplace.hint':
		"Enabling this will change the powers tab to display the icon for the power's class instead of the power's image. Useful for managing multiple lists without having to switch between them.",
	'TIDY5E.Settings.AllowCantripToBePreparedOnContext.hint':
		'The "cantrip formulas" optional rule from Tashas Cauldron of Everything allows Wizards to prepare their cantrips after a long rest in the same way that they do with leveled powers.',
	'TIDY5E.Settings.EnableSortFavoritesItemsAlphabetically.hint':
		'It enabled this setting will sort the items, features, powers alphabetically on the favorites html template',
	'TIDY5E.Settings.ColorPickerInnate.hint':
		"Select what color you want to use for 'Talent'. The transparency value '#00000000' is equivalent to disabling the color for the current context.",
	'TIDY5E.Settings.ColorPickerInnate.name': "Color Picker for 'Talent'",
	'TIDY5E.Settings.ColorPickerInnateAccent.hint':
		"Select what color you want to use for 'Talent Accent'. The transparency value '#00000000' is equivalent to disabling the color for the current context.",
	'TIDY5E.Settings.ColorPickerInnateAccent.name': "Color Picker for 'Talent Accent'",
	'TIDY5E.Settings.ColorPickerInnateOutline.hint':
		"Select what color you want to use for 'Talent Outline'. The transparency value '#00000000' is equivalent to disabling the color for the current context.",
	'TIDY5E.Settings.ColorPickerInnateOutline.name': "Color Picker for 'Talent Outline'",
};

mergeObject(game.i18n.translations, changes);
